name: application
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  animated_segmented_tab_control: ^2.0.0
  intl: ^0.20.1
  uuid: ^4.4.2
  shared_preferences: ^2.2.3
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/first_screen_images/blueSmile.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21


 
  cupertino_icons: ^1.0.8
  spider: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  
  assets:
    - assets/
    - assets/welcome_images/
    - assets/first_screen_images/
    - assets/settings_images/
  

  